name: CI

on:
  - push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Gradle verification
        run: ./gradle vefify